### ISSUE TITLE
EZspline not giving correct derivatives

### ISSUE THREAD

**Issue by zhucaoxiang** [PrincetonUniversity/STELLOPT#29] opened 2019-10-30 15:30 UTC
This is a reminder that @aaroncbader has reported a bug that EZspline doesn't give correct derivatives. More details and reproduction will be provided by @aaroncbader later.

**Comment by lazersos** [comment] 2020-05-21 08:27
@aaroncbader, @zhucaoxiang Looking back at this problem, the thing that bothers me is that the error in F grows at maximum x and y extents.  If this was a simple algebraic issue I'd expect the errors to be symmetric.  I think the issue may be with how the periodic boundary conditions are enforced.

**Comment by lazersos** [comment] 2020-05-21 10:58
OK I looked into it a bit more.  It seems that the issue is the underlying grid on which the initial function is sampled.  The function I coded up goes like cos(m*theta+n*phi) and we evaluate it from -pi to pi in the u and v dimensions.  Let me summarize my findings

- 8x8 grid has max error of 0.6% in f(u,v), and 13.6% error in df/du, df/dv, and d^2f/dudv
-12x12 grid has max error of 0.1% in f(u,v), and 6% error in df/du, df/dv, and d^2f/dudv
-16x16 grid has max error of 0.08% in f(u,v), and 4.7% error in df/du, df/dv, and d^2f/dudv
-32x32 grid has max error of 0.01% in f(u,v), and 1.5% error in df/du, df/dv, and d^2f/dudv

If I change the underlying function to be symmetric about (u,v)=(0,0) then the error becomes symmetric.  I suspect what we're seeing is just the result of using these types of splines.  

I think the takeaway message is that when going from a Fourier space representation to a spline grid we need to be careful to make sure the underlying grid possesses enough gridpoints to represent the Fourier space.  Now when it comes to representing the quantity 8xM where m is the highest harmonic gives us <1% accuracy.  However, for the derivative quantities we need much higher resolution on the order of 16xM to 32xM.

If we switch to-non-Hermite splines then our derivative terms go as
- 8x8 grid has max error of 0.1% in f(u,v), and 2.7% error in df/du, df/dv, and d^2f/dudv
-12x12 grid has max error of 0.02% in f(u,v), and 0.4% error in df/du, df/dv, and d^2f/dudv
-16x16 grid has max error of 0.005% in f(u,v), and 0.1% error in df/du, df/dv, and d^2f/dudv
-32x32 grid has max error of 0.003% in f(u,v), and 0.01% error in df/du, df/dv, and d^2f/dudv

So my general comment is that we should probably switch to non-Hermite splines in parts of the code like `stel_tools.f90` where the quantities we're splining over are defined everywhere and have no strong discontinuities.

**Comment by zhucaoxiang** [comment] 2020-05-21 15:30
@lazersos If we use other spline packages to do the same test,  will we get better convergence? Like the one from Scipy (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicHermiteSpline.html)

**Comment by lazersos** [comment] 2020-05-21 19:16
@zhucaoxiang There are many ways to do splines, but I personally would like to keep the methods in-house instead of relying on 3rd party libraries. The reason for this is that the call to a spline is often in the RHS function of an ODE integrator. Eventually we'd like to run on GPU's and then I think the splines are the first candidate to 'live' on the GPU, and I'd prefer if we didn't have to rely on 3rd parties to do this.

**Comment by lazersos** [comment] 2020-05-22 11:04
Also I'd like to be clear that EZspline can use piecewise linear, C2 cubic splines or C1 cubic splines.  The above inaccuracy in the derivative terms comes from using C1 cubic splines.  The fix is to use the C2 cubic spline methods (`spl_obj%ishermite=0`).

**Comment by lazersos** [comment] 2020-06-03 11:49
OK I did some testing and there's a complication using C2 over C1.  I tested both in the FIELDLINES code using the W7-X standard vacuum configuration as defined from the coils file.  If I use C1 splines I clearly resolve the flux surfaces, boundary 5/5 island chain, and the flux surfaces beyond that.  For the same grid resolution and construction methods I only get the core flux surfaces and no 5/5 island chain using C2. If I restrict the field generation so we don't evaluate fields larger than 5 T (mask away any spikes caused by the 1/x created by the coils being in the domain), then I get some parts of the 5/5 island chain to reappear.

So here's where we stand.  Clearly the C2 splines provide more accurate derivatives for smooth functions.  However, for field line tracing the presence of singularities or discontinuities in the domain causes ringing for C2.  This results in poor approximation of the underlying function values.  For codes like `stel_tools.f90` and `virtual_casing_mod.f90` we can use (and do) the C2 splines to provide the most accurate representation of the smooth underlying function. For the cylindrical grid quantities like those which are found in `BEAMS3D` and `FIELDLINES` we should use the C1 representation (and do).

It should be noted that the `FIELDLINES` code does not use derivatives of the splines in the ODE it solves but does use the derivative to provide a Jacobian for the ODE integrator.  This appears to work incredibly well, better than the C2 splines.

In `BEAMS3D` the ODE includes both the magnetic field and derivatives of the magnetic field.  Clearly the C1 derivatives are not as accurate as the C2 derivatives.  However, the representation of the function values is substantially better than those of the C2 given the 'real' nature of the smooth magnetic field.  So I believe we're justified in using the C1 representation.

We should entertain new 3D spline routines which can address this issue but for now I'm going to close this issue as I think it's come to a conclusion.  That conclusion is that we need to research new spline methods which are both derivative preserving and can handle functions with discontinuities.

**Closed by lazersos** 2020-06-03 11:49 UTC
Labels: bug

**Comment by dbindel** [comment] 2020-06-03 13:10
Marking this here only in case someone comes back to this thread to pic up the last point on alternate spline methods.  There are common spline families that take advantage of smoothness where present and also allow points of non-differentiability.  One of the most common (used in CAD models and in isogeometric finite element analysis) is the non-uniform rational B-spline (NURBS).

**Comment by lazersos** [comment] 2020-06-03 13:30
@dbindel I'd be happy to do this but the existing NURBS libraries don't seem particularly open source or easily interfaceable with Fortran. However, it may make a nice summer undergraduate project to write Fortran wrappers one of the NURBS C++ libraries.

**Comment by zhucaoxiang** [comment] 2020-06-03 13:52
@dbindel @lazersos I will have a summer student working on splines for coils in FOCUS. After that, I will come back to this problem and see if I can make a contribution.
